version: 2.1
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - run:
          name: Building the project
          command: |
            npm install
            yarn build
      - run:
          name: Testing the project
          command: |
            echo "No testing"