version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm build
  
  test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --delete
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: ${AWSaccessKey}
          aws-region: ${AWSRegion}
          aws-secret-access-key: ${AWSSecurityKey}
          from: build/
          overwrite: true
          to: s3://shopping-cart-react-app/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - deploy

orbs:
  aws-s3: circleci/aws-s3@1.0.16